# Generated by Django 4.2.5 on 2023-09-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumbai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.IntegerField(max_length=20),
        ),
    ]
