# Generated by Django 4.2.5 on 2023-09-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mumbai', '0002_alter_client_email_alter_client_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='AddClient',
        ),
    ]
