# Generated by Django 4.2.5 on 2023-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumbai', '0004_rename_mobile_addclient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclient',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
